### ISSUE TITLE
Using multiple thread/cores?

### ISSUE THREAD

**Issue by bhimbbiswa** [linxingchen/cobra.github.io#3]
Hi.

Thank you for making this amazing tool.

I am currently using this tool to improve my metagenomic viral contigs obtained from MegaHIT.

So, I have 80 shotgun metagenomic samples which I did coassembly in MegaHIT followed by viral contig detection by VirSorter2.

I want to extend my viral contigs by COBRA, but it not showing any progress for the past 6 days.

This is the code I use (I am using my institute cluster)
```
python cobra.py -f ~/final.contigs.fa -q ~/final.contigs.phages_combined.fna \
-o VirSorter -c ~/CoverM/For_virus/Coverage.txt -m ~/MegaHit_final.contigs.fa.All.sorted.bam \
-a megahit -mink 21 -maxk 77
```
This is the logfile
```
1. INPUT INFORMATION
# Assembler: MEGAHIT
# Min-kmer: 21
# Max-kmer: 77
# Overlap length: 77 bp
# Read mapping max mismatches for contig linkage: 2
# Query contigs: /lustre7/home/bhimbiswa/MAGs/Virus/COBRA/final-viral-combined.fa
# Whole contig set: /lustre7/home/bhimbiswa/MAGs/MegaHit/output_folder/final.contigs.fa
# Mapping file: /lustre7/home/bhimbiswa/MAGs/CoverM/For_virus/bam_files/MegaHit_final.contigs.fa.All.sorted.bam
# Coverage file: /lustre7/home/bhimbiswa/MAGs/CoverM/For_virus/Coverage.txt
# Output folder: /lustre7/home/bhimbiswa/MAGs/Virus/COBRA/Virsorter2

2. PROCESSING STEPS
[01/22] [2023/06/07 14:43:28] Reading contigs and getting the contig end sequences. A total of 1259677 contigs were imported.
[02/22] [2023/06/07 14:44:13] Getting shared contig ends.
[03/22] [2023/06/07 14:44:34] Writing contig end joining pairs.
[04/22] [2023/06/07 14:44:35] Getting contig coverage information.
[05/22] [2023/06/07 14:44:39] Getting query contig list. A total of 47249 query contigs were imported.
[06/22] [2023/06/07 14:44:40] Getting contig linkage based on sam/bam. Be patient, this may take long.
[07/22] [2023/06/08 08:29:30] Detecting self_circular contigs. 
[08/22] [2023/06/08 09:14:19] Detecting joins of contigs. 
```
I can understand that I have lots of query files that why this is very slow, but is there any way I can make this faster?

P.S.: COBRA worked fine with Phigaro viral contigs (only 285 query contigs).

**Comment by linxingchen** [comment]
Hi,

Thank you for your interest in COBRA and the question. 

Unfortunately, for now, COBRA could only detect potential joins contig by contig. I understand it is the most time-consuming step, especially when you have a lot of queries. Given that you have 80 related samples (related, I think that's why you co-assembled them), I suggest you assemble them individually for two major reasons, (1) MEGAHIT may generate too many chimeric contigs, our lab has been developing a tool to identify chimeras, MEGAHIT has the highest rate, (2) when you use COBRA on individuals, you may be able to double-check the COBRA sequences with those from different samples, given that COBRA is still under review, reviewers of your manuscript may argue if COBRA is reliable or not (though I am pretty confident about it). Alternatively, you may want to filter the length of your queries to keep those with a minimum length of, for example, 5kbp.

FYI, I tested COBRA on 6,827 queries, the [08/22] step took almost one day to finish. Your maxk is 77, I think there will be more options for the ends that are under the search for join, compared to larger kmers like 141. While on 13,204 contigs, that step took 4.5 days. So there are a lot of factors that will eventually determine the time. 

> 2. PROCESSING STEPS
> [01/22] [2023/04/20 15:48:43] Reading contigs and getting the contig end sequences. A total of 2639765 contigs were imported.
> [02/22] [2023/04/20 15:51:13] Getting shared contig ends.
> [03/22] [2023/04/20 15:52:16] Writing contig end joining pairs.
> [04/22] [2023/04/20 15:52:28] Getting contig coverage information.
> [05/22] [2023/04/20 15:52:37] Getting query contig list. A total of 13204 query contigs were imported.
> [06/22] [2023/04/20 15:52:38] Getting contig linkage based on sam/bam. Be patient, this may take long.
> [07/22] [2023/04/20 17:18:47] Detecting self_circular contigs.
> [08/22] [2023/04/20 18:36:11] Detecting joins of contigs. 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100% finished.
> [09/22] [2023/04/25 09:40:26] Saving potential joining paths.
> [10/22] [2023/04/25 09:40:35] Checking for invalid joining: sharing queries.
> [11/22] [2023/04/25 09:53:04] Getting initial joining status of each query contig.
> [12/22] [2023/04/25 09:53:07] Getting final joining status of each query contig.
> [13/22] [2023/04/25 09:53:07] Getting the joining order of contigs.
> [14/22] [2023/04/25 09:53:19] Getting retrieved contigs.
> [15/22] [2023/04/25 09:53:46] Saving joined seqeuences.
> [16/22] [2023/04/25 09:53:59] Checking for invalid joining using BLASTn: close strains.
> [17/22] [2023/04/25 10:25:24] Saving unique sequences of "Extended_circular" and "Extended_partial" for joining checking.
> [18/22] [2023/04/25 10:25:33] Getting the joining details of unique "Extended_circular" and "Extended_partial" query contigs.
> [19/22] [2023/04/25 10:25:42] Saving joining summary of "Extended_circular" and "Extended_partial" query contigs.
> [20/22] [2023/04/25 10:26:06] Saving joining status of all query contigs.
> [21/22] [2023/04/25 10:26:09] Saving self_circular contigs.
> [22/22] [2023/04/25 10:26:09] Saving the new fasta file.

I am happy to talk more.

Best,
LINXING

**Comment by bhimbbiswa** [comment]
Dear Linxing

Thank you very much for your kind reply.

I apologize for not replying earlier. I was not able to access GitHub for some time.

I will consider reassembling them individually in metaSpades.

Regards,

Bhim

**Comment by linxingchen** [comment]
> Dear Linxing
> 
> Thank you very much for your kind reply.
> 
> I apologize for not replying earlier. I was not able to access GitHub for some time.
> 
> I will consider reassembling them individually in metaSpades.
> 
> Regards,
> 
> Bhim

Hi Bhim, thanks for letting me know. I am happy to help further, just let me know when needed. 

Best, 
LINXING
